import { Inter } from 'next/font/google';
import Script from 'next/script';

import './globals.css';
import './style.css';
import Navbar from '@/component/Navbar';
import Footer from '@/component/Footer';

const inter = Inter({ 
  subsets: ['latin']
 })

export const metadata = {
  title: 'Food Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin='' />
       

      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />


        <Script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="..."
  crossOrigin=''// Change `crossorigin` to `crossOrigin`
  defer
/>

        </body>

    </html>
  )
}
